# Data 
from https://www.cs.toronto.edu/~kriz/cifar.html
Cifar-10 dataset
<br>
used 7zip to unzip .gz file first

In [ ]:
import pickle

In [18]:
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict1 = pickle.load(fo, encoding='bytes')
    return dict1

In [19]:
batch1 = unpickle('cifar-10-batches-py/data_batch_1')

In [21]:
batch1.keys()

dict_keys([b'batch_label', b'labels', b'data', b'filenames'])

In [23]:
batch1[b'batch_label']

b'training batch 1 of 5'

In [24]:
batch1[b'labels']

[6,
 9,
 9,
 4,
 1,
 1,
 2,
 7,
 8,
 3,
 4,
 7,
 7,
 2,
 9,
 9,
 9,
 3,
 2,
 6,
 4,
 3,
 6,
 6,
 2,
 6,
 3,
 5,
 4,
 0,
 0,
 9,
 1,
 3,
 4,
 0,
 3,
 7,
 3,
 3,
 5,
 2,
 2,
 7,
 1,
 1,
 1,
 2,
 2,
 0,
 9,
 5,
 7,
 9,
 2,
 2,
 5,
 2,
 4,
 3,
 1,
 1,
 8,
 2,
 1,
 1,
 4,
 9,
 7,
 8,
 5,
 9,
 6,
 7,
 3,
 1,
 9,
 0,
 3,
 1,
 3,
 5,
 4,
 5,
 7,
 7,
 4,
 7,
 9,
 4,
 2,
 3,
 8,
 0,
 1,
 6,
 1,
 1,
 4,
 1,
 8,
 3,
 9,
 6,
 6,
 1,
 8,
 5,
 2,
 9,
 9,
 8,
 1,
 7,
 7,
 0,
 0,
 6,
 9,
 1,
 2,
 2,
 9,
 2,
 6,
 6,
 1,
 9,
 5,
 0,
 4,
 7,
 6,
 7,
 1,
 8,
 1,
 1,
 2,
 8,
 1,
 3,
 3,
 6,
 2,
 4,
 9,
 9,
 5,
 4,
 3,
 6,
 7,
 4,
 6,
 8,
 5,
 5,
 4,
 3,
 1,
 8,
 4,
 7,
 6,
 0,
 9,
 5,
 1,
 3,
 8,
 2,
 7,
 5,
 3,
 4,
 1,
 5,
 7,
 0,
 4,
 7,
 5,
 5,
 1,
 0,
 9,
 6,
 9,
 0,
 8,
 7,
 8,
 8,
 2,
 5,
 2,
 3,
 5,
 0,
 6,
 1,
 9,
 3,
 6,
 9,
 1,
 3,
 9,
 6,
 6,
 7,
 1,
 0,
 9,
 5,
 8,
 5,
 2,
 9,
 0,
 8,
 8,
 0,
 6,
 9,
 1,
 1,
 6,
 3,
 7,
 6,
 6,
 0,
 6,
 6,
 1,
 7,
 1,
 5,
 8,
 3,
 6,
 6,
 8,
 6,
 8,
 4,
 6,
 6,


In [29]:
batch1[b'data'].shape # each batch is 32 by 32 pixels, with corresponding RGB (in that order) values --> 32*32*3 = 3072 values to represent

(10000, 3072)

In [31]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [1]:
import cv2

# testing out showing an image using opencv

In [43]:
a = cv2.imread('rak_turtles.jpg', cv2.IMREAD_UNCHANGED)

In [50]:
a.shape

(672, 672, 3)

In [49]:
a[:,:,0]

array([[216, 217, 217, ..., 233, 235, 237],
       [218, 219, 219, ..., 229, 231, 232],
       [219, 220, 221, ..., 229, 229, 229],
       ...,
       [206, 205, 205, ..., 193, 199, 200],
       [205, 205, 204, ..., 197, 197, 197],
       [204, 203, 202, ..., 194, 191, 194]], dtype=uint8)

In [51]:
cv2.imshow('rak', a)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [52]:
a[55,55]

array([233, 236, 234], dtype=uint8)

In [57]:
a[1,:]

array([[218, 225, 222],
       [219, 226, 223],
       [219, 226, 223],
       ...,
       [229, 233, 234],
       [231, 235, 236],
       [232, 236, 237]], dtype=uint8)

# Import model

In [24]:
import cv2
import numpy as np

In [5]:
cv2.__version__

'4.2.0'

In [25]:
import os

In [26]:
os.path.abspath("yolov3_coco/yolov3.weights") # grab absolute paths just in case can't find by relative path

'C:\\Users\\gl127\\Downloads\\yolov3_coco\\yolov3.weights'

In [27]:
os.path.abspath("yolov3_coco/yolov3.cfg") # grab absolute paths just in case

'C:\\Users\\gl127\\Downloads\\yolov3_coco\\yolov3.cfg'

## Model

In [28]:
model1 = cv2.dnn.readNet(model = "C:\\Users\\gl127\\Downloads\\yolov3_coco\\yolov3.weights", 
                         config = "C:\\Users\\gl127\\Downloads\\yolov3_coco\\yolov3.cfg")

# make sure .cfg is a .cfg file and not something like a .txt file... took me 3 hours to remember to fix that...
# https://www.tensorflow.org/resources/models-datasets if you want to test out other pre-trained models later
# https://docs.opencv.org/4.2.0/d6/d0f/group__dnn.html#ga3b34fe7a29494a6a4295c169a7d32422 for documentation on models it can use

## Classes

In [29]:
a = open("yolov3_coco/coco.names", "r") # our classes

In [30]:
class_list = [i for i in a.readlines()] # can't do b = a.readlines() because a.readlines() will loop through the list, while removing each term afterwards, leaving b equal to an empty list
class_list

['person\n',
 'bicycle\n',
 'car\n',
 'motorbike\n',
 'aeroplane\n',
 'bus\n',
 'train\n',
 'truck\n',
 'boat\n',
 'traffic light\n',
 'fire hydrant\n',
 'stop sign\n',
 'parking meter\n',
 'bench\n',
 'bird\n',
 'cat\n',
 'dog\n',
 'horse\n',
 'sheep\n',
 'cow\n',
 'elephant\n',
 'bear\n',
 'zebra\n',
 'giraffe\n',
 'backpack\n',
 'umbrella\n',
 'handbag\n',
 'tie\n',
 'suitcase\n',
 'frisbee\n',
 'skis\n',
 'snowboard\n',
 'sports ball\n',
 'kite\n',
 'baseball bat\n',
 'baseball glove\n',
 'skateboard\n',
 'surfboard\n',
 'tennis racket\n',
 'bottle\n',
 'wine glass\n',
 'cup\n',
 'fork\n',
 'knife\n',
 'spoon\n',
 'bowl\n',
 'banana\n',
 'apple\n',
 'sandwich\n',
 'orange\n',
 'broccoli\n',
 'carrot\n',
 'hot dog\n',
 'pizza\n',
 'donut\n',
 'cake\n',
 'chair\n',
 'sofa\n',
 'pottedplant\n',
 'bed\n',
 'diningtable\n',
 'toilet\n',
 'tvmonitor\n',
 'laptop\n',
 'mouse\n',
 'remote\n',
 'keyboard\n',
 'cell phone\n',
 'microwave\n',
 'oven\n',
 'toaster\n',
 'sink\n',
 'refrigerator

In [31]:
a.close()

In [32]:
# could have done:
# with open("yolov3_coco/coco.names", "r") as f:
#     classes_list = [i for i in f.readlines()]

In [33]:
class_list = [i.strip() for i in class_list]
class_list

['person',
 'bicycle',
 'car',
 'motorbike',
 'aeroplane',
 'bus',
 'train',
 'truck',
 'boat',
 'traffic light',
 'fire hydrant',
 'stop sign',
 'parking meter',
 'bench',
 'bird',
 'cat',
 'dog',
 'horse',
 'sheep',
 'cow',
 'elephant',
 'bear',
 'zebra',
 'giraffe',
 'backpack',
 'umbrella',
 'handbag',
 'tie',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard',
 'surfboard',
 'tennis racket',
 'bottle',
 'wine glass',
 'cup',
 'fork',
 'knife',
 'spoon',
 'bowl',
 'banana',
 'apple',
 'sandwich',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza',
 'donut',
 'cake',
 'chair',
 'sofa',
 'pottedplant',
 'bed',
 'diningtable',
 'toilet',
 'tvmonitor',
 'laptop',
 'mouse',
 'remote',
 'keyboard',
 'cell phone',
 'microwave',
 'oven',
 'toaster',
 'sink',
 'refrigerator',
 'book',
 'clock',
 'vase',
 'scissors',
 'teddy bear',
 'hair dryer',
 'toothbrush']

# Importing an image to test with

In [83]:
cat_test = cv2.imread('C:\\Users\\gl127\\Downloads\\yolov3_coco\\images\\cats1.jpg', cv2.IMREAD_UNCHANGED)
cat_test = cv2.resize(src = cat_test, dsize = None, fx = 0.15, fy = 0.15)
cv2.imshow('cats', cat_test)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Preprocessing an image so it can be a properly formatted input for the model

In [86]:
blob = cv2.dnn.blobFromImage(image = cat_test,
                        scalefactor = 0.00392, # 1/sigma for normalizing
                        size = (416, 416), # seems like 609, 609 doesn't work?
                        mean = (0, 0, 0), # mean (R,G,B) values for normalizing; will be subtracted from each channel
                        swapRB = True, # need to swap red and blue because mean subtracts RGB but opencv read in BGR
                        crop = False) # don't crop when resizing

# good explanation for each parameter: https://www.pyimagesearch.com/2017/11/06/deep-learning-opencvs-blobfromimage-works/
# with mean = 0,0,0 and scalefactor = 1/255, we're just resizing the image then dividing all BGR values by 255
# so input values range in [0, 1] at the moment

In [87]:
blob.shape # number of images, channels, width, height

(1, 3, 416, 416)

In [79]:
blob

array([[[[0.882     , 0.88592   , 0.88984   , ..., 0.65464   ,
          0.69384   , 0.72128   ],
         [0.88592   , 0.88592   , 0.88592   , ..., 0.66248   ,
          0.70952   , 0.74480003],
         [0.88592   , 0.88592   , 0.882     , ..., 0.67424   ,
          0.72912   , 0.76832   ],
         ...,
         [0.63112   , 0.61936   , 0.59976   , ..., 0.29792   ,
          0.29008   , 0.28616   ],
         [0.57624   , 0.57232   , 0.56448   , ..., 0.29792   ,
          0.28224   , 0.2744    ],
         [0.56448   , 0.58016   , 0.60760003, ..., 0.32536   ,
          0.29792   , 0.27832   ]],

        [[0.75656   , 0.76048   , 0.7644    , ..., 0.52136   ,
          0.5684    , 0.59976   ],
         [0.75656   , 0.75656   , 0.76048   , ..., 0.5292    ,
          0.58408   , 0.61936   ],
         [0.76048   , 0.76048   , 0.76048   , ..., 0.53704   ,
          0.59584   , 0.63896   ],
         ...,
         [0.50568   , 0.49784002, 0.49      , ..., 0.25088   ,
          0.24304   , 0.2

# Pass image through NN

In [80]:
## Need output layers to pass blobs through **************CHECK WHAT THE OUTPUTS OF EACH LOOK LIKE

In [89]:
layer_names = model1.getLayerNames() # yolov3 architecture has 3 outputs at layers 82, 94, 106 labeled yolo_82, yolo_94, yolo_106
layer_names

['conv_0',
 'bn_0',
 'relu_1',
 'conv_1',
 'bn_1',
 'relu_2',
 'conv_2',
 'bn_2',
 'relu_3',
 'conv_3',
 'bn_3',
 'relu_4',
 'shortcut_4',
 'conv_5',
 'bn_5',
 'relu_6',
 'conv_6',
 'bn_6',
 'relu_7',
 'conv_7',
 'bn_7',
 'relu_8',
 'shortcut_8',
 'conv_9',
 'bn_9',
 'relu_10',
 'conv_10',
 'bn_10',
 'relu_11',
 'shortcut_11',
 'conv_12',
 'bn_12',
 'relu_13',
 'conv_13',
 'bn_13',
 'relu_14',
 'conv_14',
 'bn_14',
 'relu_15',
 'shortcut_15',
 'conv_16',
 'bn_16',
 'relu_17',
 'conv_17',
 'bn_17',
 'relu_18',
 'shortcut_18',
 'conv_19',
 'bn_19',
 'relu_20',
 'conv_20',
 'bn_20',
 'relu_21',
 'shortcut_21',
 'conv_22',
 'bn_22',
 'relu_23',
 'conv_23',
 'bn_23',
 'relu_24',
 'shortcut_24',
 'conv_25',
 'bn_25',
 'relu_26',
 'conv_26',
 'bn_26',
 'relu_27',
 'shortcut_27',
 'conv_28',
 'bn_28',
 'relu_29',
 'conv_29',
 'bn_29',
 'relu_30',
 'shortcut_30',
 'conv_31',
 'bn_31',
 'relu_32',
 'conv_32',
 'bn_32',
 'relu_33',
 'shortcut_33',
 'conv_34',
 'bn_34',
 'relu_35',
 'conv_35',
 'b

In [90]:
outlayer_place = model1.getUnconnectedOutLayers() # grab index + 1 of those output layers (i.e. 254th place is indexed 253)
outlayer_place

array([[200],
       [227],
       [254]], dtype=int32)

In [91]:
outlayer_place[0][0] # outlayer[0] gives array of array

200

In [92]:
output_layers = [layer_names[i[0]-1] for i in outlayer_place] # need -1 to get index
output_layers

['yolo_82', 'yolo_94', 'yolo_106']

In [93]:
model1.setInput(blob) # "sets the new input value for the network"

In [94]:
preds = model1.forward(output_layers) # passes input through network to get output, they call the output "output blobs"

In [106]:
preds

[array([[0.04916982, 0.03934744, 0.27945086, ..., 0.        , 0.        ,
         0.        ],
        [0.05503102, 0.02940258, 0.21405414, ..., 0.        , 0.        ,
         0.        ],
        [0.05547196, 0.03250728, 0.9422953 , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.9592709 , 0.9510122 , 0.5031428 , ..., 0.        , 0.        ,
         0.        ],
        [0.96162486, 0.96473193, 0.32699743, ..., 0.        , 0.        ,
         0.        ],
        [0.9645796 , 0.9600416 , 0.84028554, ..., 0.        , 0.        ,
         0.        ]], dtype=float32),
 array([[0.02290254, 0.02118389, 0.05898774, ..., 0.        , 0.        ,
         0.        ],
        [0.01911967, 0.02337484, 0.29005554, ..., 0.        , 0.        ,
         0.        ],
        [0.02639358, 0.02061865, 0.089763  , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.97454035, 0.9758494 , 0.04671209, ..., 0.        , 0.        ,
         0.        

In [105]:
len(preds) # list of 3 arrays

3

In [102]:
preds[0].shape # first: 13x13 feature map

(507, 85)

In [103]:
preds[1].shape # second: 26x26 feature map

(2028, 85)

In [104]:
preds[2].shape # third: 52x52 feature map

(8112, 85)

# Get info from outputs

In [ ]:
## Need to grab size/shape of image because the neural network outputs normalized bounding box dimensions, i.e. [0,1]

In [84]:
cat_test.shape # (490, 367, 3)

(490, 367, 3)

In [85]:
height = cat_test.shape[0]
width = cat_test.shape[1]
n_channels = cat_test.shape[2] # remember opencv reads images in BGR, not RGB or BGRa

In [134]:
boxes = []
class_probs_list = []
class_ids = []

for pred in preds: 
    for detect_loc_probs in pred: # each detect_loc_probs contains 0: normalized center x-coord of detected obj's bounding box, 
                                # 1: normalized center y-coord of detected obj's bounding box, 2: normalized width of detected obj's bounding box,
                                # 3: normalized height of detected obj's bounding box
        class_probs = detect_loc_probs[5:] # probabilities of being each class (out of the 80 classes), which are the last 80 values
        class_idx = np.argmax(class_probs) # what is it most likely to be? -> grab that index to find 
        max_prob = class_probs[class_idx] # the highest probability
        
        if max_prob > 0.5: # typically 0.5
            center_x = int(detect_loc_probs[0] * width) # detect_loc_probs[0] are numpy.float32s
            center_y = int(detect_loc_probs[1] * height) # grabbing "rescaled" lengths back
            w = int(detect_loc_probs[2] * width) # center_x, center_y, w, and h can define a bounding box but cv.rectangle uses top left corner to bottom right
            h = int(detect_loc_probs[3] * height)
            top_left_x = center_x - w/2
            top_left_y = center_y - h/2
            
            # keep track of instances/bounding boxes where there is likely to be an object
            boxes.append([w, h, top_left_x, top_left_y])
            # keep track of that instance's probability and class
            class_probs_list.append(max_prob)
            class_ids.append(class_idx)
            

In [127]:
# preds[i] = group of predicted objs, one group for each feature map size
# preds[i][j] = one detect_loc_probs (the info)
# preds[i][j][0] = norm center x coord of bounding box
# preds[i][j][1] = norm center y coord
# preds[i][j][2] = norm width
# preds[i][j][3] = norm height
# preds[i][j][5-84] = probabilities for each class
# preds[i][j][4] = object probability?

In [129]:
preds[2][5000][4]

9.472272e-08

In [ ]:
np.random.random_integers(low = 0, 
                          high = 255, 
                          size = (len(class_list), 3))